### ISSUE TITLE
Inits

### ISSUE THREAD

**Issue by kaskr** [kaskr/tmbstan#2]
From Cole:

I think you should add some more flexibility when it comes to what inits you can pass. Now it's only a list, and I get weird errors if I specify the wrong thing. I suggest adding some checks in there and make it allow the same things as stan.

**Comment by colemonnahan** [comment]
Specifically, this code should work:

````
runExample("simple")
init.fn <- function() list(beta=rnorm(2), logsdu=rnorm(1), logsd0=rnorm(1),
                           u=rnorm(114))
fit <- tmbstan(obj=obj, init=init.fn) 
````
which currently throws this meaningless error:

````
SAMPLING FOR MODEL 'tmb_generic' NOW (CHAIN 1).
variable y missing
[1] "Error in sampler$call_sampler(args_list[[i]]) : variable y missing"
[1] "error occurred during calling the sampler; sampling not done"
````

The function is called for each chain being run. This matches Stan and more generally JAGS/BUGS/etc. since it is recommended to initiate from random diffuse points. From the Stan help:

>      init: Can be the digit '0', the strings '"0"' or '"random"', a
 >        function that returns a named list, or a list of named lists

I also think it should throw an error or warning at least when you pass a list that doesn't match the number of chains. So like this

````
inits <- lapply(1:4, function(x) init.fn())
fit <- tmbstan(obj=obj, init=inits)
inits <- lapply(1:3, function(x) init.fn())
fit <- tmbstan(obj=obj, init=inits)
````
Both of these run. What is it doing for chain 4 in the second example here? Using the MLE? Stan throws an error when doing this:

````
Error in config_argss(chains = chains, iter = iter, warmup = warmup, thin = thin,  : 
  initial value list mismatchs number of chains
error in specifying arguments; sampling not done
````

I'd also consider adding a warning if the user doesn't specify an init and defaults to the MLE. That's pretty discouraged.

**Comment by kaskr** [comment]
@colemonnahan  Should be fixed now.

**Comment by colemonnahan** [comment]
Yep, works on my end.

**Comment by torarneoigard** [comment]
Hi,
Thanks for great package. I've got a question related to inits.
As far as I understand if you have optimized your object, e.g. the simple-model, you can use the ML estimates as initial values by doing
fit <- tmbstan(obj,init = "last.par.best",chains = 1).

If I then use get_inits(fit) I would assume that those values are the same as found in the opt object, or have I misunderstood? They are different.

The reason for asking this is that when using tmbstan on a custom model I get the following error message:

"Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value."

That is why I'd like to start from the ML values. 

Would the error message above be the reason for this error message:

"Error in .Call("is_Null_NS", ns) : 
  "is_Null_NS" not resolved from current namespace (rstan)
In addition: Warning message:
There were 1000 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup"

Because of this I'm not able to create that fit object.

**Comment by kaskr** [comment]
Try `init=list("last.par.best")`.

**Update**
Documentation needs to be fixed.

**Comment by torarneoigard** [comment]
Thank you very much! It worked!

This might not be related to tmbstan but rather rstan? Get this following error message:

Error in .Call("is_Null_NS", ns) : 
  "is_Null_NS" not resolved from current namespace (rstan)
In addition: Warning messages:
1: There were 97 divergent transitions after warmup. Increasing adapt_delta above 0.8 may help. See
http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup 
2: There were 902 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth above 10. See
http://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded 

I have an age structured population dynamics model. First tried simulating with all parameters that is estimated. Then tried to increase adapt_delta to 0.99 and maximum tree depth to 15 and same things happened. Then tried the same but just simulated from one of the parameters in the model by specifying the "par" option. Same thing happened. Have you encountered this before? The model converges just fine. Is it too complicated to simulate from?

**Comment by colemonnahan** [comment]
Yes, those are Rstan and NUTS warning you're getting, having nothing to do
with TMB. Usually those messages suggest some part of the model is very
difficult to sample from, and that convergence is unlikely. Are you sure
it's converging? Your Rhat's are all close to 1? Are the divergent
transitions clustered when you plot them with pairs? If so, that's bad.

Is it possible to get negative biomass in your model? If so, what happens
to the likelihood? That's my first guess as to the cause.

**Comment by torarneoigard** [comment]
Thank you for your response. When I mean convergence I meant that the optimization of the TMB object using nlminb-converges. I'm not able to see the Rhats and if the divergent transitions are clustered as when running fit<- tmbstan(...) it won't provide the fit-object due to the error message mentioned earlier. 

In regards to negative biomass. We do not have a constraint on it. We estimate the number of fish N on logscale, i.e.,

logN(y,a)=logN(y-1,a-1)-F(y-1,a-1)-M;

where F is fishing mortality and M is natural mortality.

**Comment by colemonnahan** [comment]
Maybe @kaskr can help with this error:

"Error in .Call("is_Null_NS", ns) :
"is_Null_NS" not resolved from current namespace (rstan)

I've never seen this. You have the most recent versions of rstan and
tmbstan? Can you run other models without this error in tmbstan?

**Comment by kaskr** [comment]
If @colemonnahan  hasn't seen the error message before, it's quite likely a bug in tmbstan. @torarneoigard  Would you be willing to construct a minimal reproducible example ?

**Comment by torarneoigard** [comment]
I use rstan version 2.17.3 from 20. January. Seem to be the latest version.

I use tmbstan version 1.0.0 downloaded from GitHub. This also seem to be the latest version.

I also use TMB 1.7.12

I tried simplifying the model I have. It has many random effects, but those can be switched on and off. So turned off most of them and tried to simulate from just one of the parameters. Still get the "Error in .Call..." error message and no object from tmbstan. 

I tried the examples that came along with TMB and also I tried the SAM example and had no problems.

**Comment by torarneoigard** [comment]
@kaskr Sure, the model and data files can be downloaded from GitHub

https://github.com/torarneoigard/SCA_mentella.git

The files you want to look at is the SCA_mentella_Do_It_All.R and run it until you get to the line
source("SCA_mentella_model.R"). 

You probably don't want to source that one, but you can. Otherwise you can open the file SCA_mentella_model.R and run it stepwise until the optimization. 

In the SCA_mentella_Do_It_All.R you can turn on and off random effects.

Was this something you had in mind or is it too elaborate? 

When running the tmbstan I used:
fit <- tmbstan(obj,par = c("logSigmalogNA1"),init = list("last.par.best"),control = list(adapt_delta = 0.999,max_treedepth = 15),chains = 1)

I tried with adapt_delta = 0.85 and max_treedept = 10 as well (the default values).

**Comment by kaskr** [comment]
@torarneoigard  I tried your example but cannot reproduce the error message.

**Comment by torarneoigard** [comment]
@kaskr Wow, that is quick. So you ran the code up to the optimization in the SCA_mentella_model.R and did not turn off any of the random effects in the SCA_mentella_Do_It_All.R file.

Then you ran the tmbstan on the TMB object and it all went well? This is strange.

I have done this under linux, ubuntu 16.04 and using the clang compilatior.

I tried doing it on windows and it all went well.

Thank you for testing this!

**Comment by kaskr** [comment]
@torarneoigard  'and it all went well'...  Does that mean you're not having the

> "Error in .Call("is_Null_NS", ns) :
> "is_Null_NS" not resolved from current namespace (rstan)

error any more ?

**Comment by torarneoigard** [comment]
@kaskr sorry about the vague response. When I use Linux I get the error message, but not when using windows.

**Comment by kaskr** [comment]
@torarneoigard  It makes no sense at all that `rstan` can't find one of its own functions. FWIW, currently my best guess would be you have a broken installation of `rstan`. Could be a side effect of using a different C++ compiler (with different compiler flags) than the one used by R itself when building rstan...

I'll put this on hold for now until I have a reproducible example.

**Comment by torarneoigard** [comment]
@kaskr I will look into what you suggest. Thank you very much for checking this out. I really appreciate it. It helped med moving forward as I can use windows for the moment but will definitely check if I have a broken installation of rstan an try using a different compiler than clang. If I'm able to provide a reproducible example I'll let you know.

**Comment by catarinawor** [comment]
Hey there, 
I just ran into the same problem on a mac - El Capitan. Somehow it fixed itself when I restarted R.
